server:
  port: 8081

spring:
  application:
    name: eclient2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH.mm.ss} - %msg%n'