server:
  port: 0

spring:
  application:
    name: eclient

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true
    # unique id for each instance
    instance-id: '${spring.application.name}: ${random.uuid}'

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH.mm.ss} - %msg%n'